; AUTO-GENERATED FILE. DO NOT EDIT.
; Generator: tools/generate_game_catalog_autoit.py
; Inputs: config/game/current-client.json, config/game/battle-surfaces.json, config/game/guardians.json, config/game/heroes.json, config/game/screen-states.json
;
; This file is distributed under the terms of the GNU GPL v3.
#include-once

Global Const $CURRENT_GAME_SCHEMA_VERSION = 1
Global Const $CURRENT_GAME_AS_OF = "2026-08-06"
Global Const $CURRENT_GAME_VERIFIED_THROUGH = "2026-07-09"
Global Const $CURRENT_GAME_MAX_TOWN_HALL = 18
Global Const $CURRENT_GAME_HOME_HERO_COUNT = 6
Global Const $CURRENT_GAME_MAX_ACTIVE_HERO_SLOTS = 4
Global Const $CURRENT_GAME_GUARDIAN_COUNT = 3
Global Const $CURRENT_GAME_MAX_ACTIVE_GUARDIANS = 1

Global Enum $eGameSourceId, $eGameSourceDate, $eGameSourceTitle, $eGameSourceUrl, $eGameSourceColumnCount
Global Enum $eGameHeroId, $eGameHeroLabel, $eGameHeroUnlockTownHall, $eGameHeroMovement, $eGameHeroSourceId, $eGameHeroSourceConfidence, $eGameHeroFixtureIds, $eGameHeroAvailabilityDate, $eGameHeroActiveSlotEligible, $eGameHeroColumnCount
Global Enum $eGameGuardianId, $eGameGuardianLabel, $eGameGuardianUnlockTownHall, $eGameGuardianSourceId, $eGameGuardianBuilderRequired, $eGameGuardianUnavailableWhileUpgrading, $eGameGuardianCompletedLevelDefends, $eGameGuardianFixtureIds, $eGameGuardianColumnCount
Global Enum $eGameBattleId, $eGameBattleLabel, $eGameBattleSourceId, $eGameBattleEngineRoute, $eGameBattleParentSurface, $eGameBattleMinimumTownHall, $eGameBattleSchedule, $eGameBattleBudgetKind, $eGameBattleBudgetValue, $eGameBattleBudgetUnit, $eGameBattleTrophyEffect, $eGameBattleFixtureIds, $eGameBattleRecognitionStatus, $eGameBattleExecutionStatus, $eGameBattleLegacyFallbackAllowed, $eGameBattleShadowBase, $eGameBattleColumnCount
Global Enum $eGameScreenId, $eGameScreenCategory, $eGameScreenSourceId, $eGameScreenCapabilityIds, $eGameScreenFixtureIds, $eGameScreenBlocking, $eGameScreenRecognitionStatus, $eGameScreenHandlerStatus, $eGameScreenSafeDefaultAction, $eGameScreenRetryLimit, $eGameScreenAppearsAfterSeconds, $eGameScreenSpeedMultiplier, $eGameScreenColumnCount

Global $g_aCurrentGameSources[11][$eGameSourceColumnCount]
Global $g_aCurrentGameHeroes[6][$eGameHeroColumnCount]
Global $g_aCurrentGameGuardians[3][$eGameGuardianColumnCount]
Global $g_aCurrentGameBattleSurfaces[7][$eGameBattleColumnCount]
Global $g_aCurrentGameScreenStates[17][$eGameScreenColumnCount]
Global $__g_bCurrentGameCatalogInitialized = False

Func _InitializeCurrentGameCatalogGenerated()
	If $__g_bCurrentGameCatalogInitialized Then Return
	$g_aCurrentGameSources[0][$eGameSourceId] = "town-hall-13-2019-12-09"
	$g_aCurrentGameSources[0][$eGameSourceDate] = "2019-12-09"
	$g_aCurrentGameSources[0][$eGameSourceTitle] = "December Update - Patch Notes"
	$g_aCurrentGameSources[0][$eGameSourceUrl] = "https://supercell.com/en/games/clashofclans/blog/news/december-update-patch-notes/"
	$g_aCurrentGameSources[1][$eGameSourceId] = "town-hall-17-2024-11-25"
	$g_aCurrentGameSources[1][$eGameSourceDate] = "2024-11-25"
	$g_aCurrentGameSources[1][$eGameSourceTitle] = "The Town Hall 17 Update Is Here"
	$g_aCurrentGameSources[1][$eGameSourceUrl] = "https://supercell.com/en/games/clashofclans/blog/game-updates/the-town-hall-17-update-is-here-2/"
	$g_aCurrentGameSources[2][$eGameSourceId] = "clash-anytime-2025-03-24"
	$g_aCurrentGameSources[2][$eGameSourceDate] = "2025-03-24"
	$g_aCurrentGameSources[2][$eGameSourceTitle] = "Welcome to Clash Anytime Update"
	$g_aCurrentGameSources[2][$eGameSourceUrl] = "https://supercell.com/en/games/clashofclans/blog/release-notes/welcome-to-clash-anytime-update/"
	$g_aCurrentGameSources[3][$eGameSourceId] = "lets-get-crafty-2025-06-16"
	$g_aCurrentGameSources[3][$eGameSourceDate] = "2025-06-16"
	$g_aCurrentGameSources[3][$eGameSourceTitle] = "Welcome to Let's Get Crafty Update"
	$g_aCurrentGameSources[3][$eGameSourceUrl] = "https://supercell.com/en/games/clashofclans/blog/release-notes/welcome-to-lets-get-crafty-update/"
	$g_aCurrentGameSources[4][$eGameSourceId] = "ranked-2025-10-06"
	$g_aCurrentGameSources[4][$eGameSourceDate] = "2025-10-06"
	$g_aCurrentGameSources[4][$eGameSourceTitle] = "Get Ready for Ranked"
	$g_aCurrentGameSources[4][$eGameSourceUrl] = "https://supercell.com/en/games/clashofclans/blog/release-notes/get-ready-for-ranked-update/"
	$g_aCurrentGameSources[5][$eGameSourceId] = "town-hall-18-2025-11-17"
	$g_aCurrentGameSources[5][$eGameSourceDate] = "2025-11-17"
	$g_aCurrentGameSources[5][$eGameSourceTitle] = "Town Hall 18 Crash Lands"
	$g_aCurrentGameSources[5][$eGameSourceUrl] = "https://supercell.com/en/games/clashofclans/blog/release-notes/town-hall-18-crash-lands-update/"
	$g_aCurrentGameSources[6][$eGameSourceId] = "february-2026-02-23"
	$g_aCurrentGameSources[6][$eGameSourceDate] = "2026-02-23"
	$g_aCurrentGameSources[6][$eGameSourceTitle] = "The February Update Has Escaped"
	$g_aCurrentGameSources[6][$eGameSourceUrl] = "https://supercell.com/en/games/clashofclans/blog/release-notes/the-february-update-has-escaped/"
	$g_aCurrentGameSources[7][$eGameSourceId] = "sound-of-clash-2026-04-27"
	$g_aCurrentGameSources[7][$eGameSourceDate] = "2026-04-27"
	$g_aCurrentGameSources[7][$eGameSourceTitle] = "The Sound of Clash Update Is Here"
	$g_aCurrentGameSources[7][$eGameSourceUrl] = "https://supercell.com/en/games/clashofclans/blog/release-notes/the-sound-of-clash-update/"
	$g_aCurrentGameSources[8][$eGameSourceId] = "may-update-2026-05-26"
	$g_aCurrentGameSources[8][$eGameSourceDate] = "2026-05-26"
	$g_aCurrentGameSources[8][$eGameSourceTitle] = "May Update"
	$g_aCurrentGameSources[8][$eGameSourceUrl] = "https://supercell.com/en/games/clashofclans/blog/release-notes/may-update/"
	$g_aCurrentGameSources[9][$eGameSourceId] = "anime-fury-2026-06-15"
	$g_aCurrentGameSources[9][$eGameSourceDate] = "2026-06-15"
	$g_aCurrentGameSources[9][$eGameSourceTitle] = "The Anime Fury Update Is Here"
	$g_aCurrentGameSources[9][$eGameSourceUrl] = "https://supercell.com/en/games/clashofclans/blog/release-notes/the-anime-fury-update-is-here/"
	$g_aCurrentGameSources[10][$eGameSourceId] = "july-balance-2026-07-09"
	$g_aCurrentGameSources[10][$eGameSourceDate] = "2026-07-09"
	$g_aCurrentGameSources[10][$eGameSourceTitle] = "July Balance Update"
	$g_aCurrentGameSources[10][$eGameSourceUrl] = "https://supercell.com/en/games/clashofclans/blog/news/july-balance-update/"
	$g_aCurrentGameHeroes[0][$eGameHeroId] = "barbarian-king"
	$g_aCurrentGameHeroes[0][$eGameHeroLabel] = "Barbarian King"
	$g_aCurrentGameHeroes[0][$eGameHeroUnlockTownHall] = 4
	$g_aCurrentGameHeroes[0][$eGameHeroMovement] = "ground"
	$g_aCurrentGameHeroes[0][$eGameHeroSourceId] = "may-update-2026-05-26"
	$g_aCurrentGameHeroes[0][$eGameHeroSourceConfidence] = "official-explicit"
	$g_aCurrentGameHeroes[0][$eGameHeroFixtureIds] = "heroes.hall.six"
	$g_aCurrentGameHeroes[0][$eGameHeroAvailabilityDate] = ""
	$g_aCurrentGameHeroes[0][$eGameHeroActiveSlotEligible] = True
	$g_aCurrentGameHeroes[1][$eGameHeroId] = "archer-queen"
	$g_aCurrentGameHeroes[1][$eGameHeroLabel] = "Archer Queen"
	$g_aCurrentGameHeroes[1][$eGameHeroUnlockTownHall] = 8
	$g_aCurrentGameHeroes[1][$eGameHeroMovement] = "ground"
	$g_aCurrentGameHeroes[1][$eGameHeroSourceId] = "town-hall-17-2024-11-25"
	$g_aCurrentGameHeroes[1][$eGameHeroSourceConfidence] = "official-explicit"
	$g_aCurrentGameHeroes[1][$eGameHeroFixtureIds] = "heroes.hall.six"
	$g_aCurrentGameHeroes[1][$eGameHeroAvailabilityDate] = ""
	$g_aCurrentGameHeroes[1][$eGameHeroActiveSlotEligible] = True
	$g_aCurrentGameHeroes[2][$eGameHeroId] = "minion-prince"
	$g_aCurrentGameHeroes[2][$eGameHeroLabel] = "Minion Prince"
	$g_aCurrentGameHeroes[2][$eGameHeroUnlockTownHall] = 9
	$g_aCurrentGameHeroes[2][$eGameHeroMovement] = "air"
	$g_aCurrentGameHeroes[2][$eGameHeroSourceId] = "town-hall-17-2024-11-25"
	$g_aCurrentGameHeroes[2][$eGameHeroSourceConfidence] = "official-explicit"
	$g_aCurrentGameHeroes[2][$eGameHeroFixtureIds] = "heroes.hall.six"
	$g_aCurrentGameHeroes[2][$eGameHeroAvailabilityDate] = ""
	$g_aCurrentGameHeroes[2][$eGameHeroActiveSlotEligible] = True
	$g_aCurrentGameHeroes[3][$eGameHeroId] = "grand-warden"
	$g_aCurrentGameHeroes[3][$eGameHeroLabel] = "Grand Warden"
	$g_aCurrentGameHeroes[3][$eGameHeroUnlockTownHall] = 11
	$g_aCurrentGameHeroes[3][$eGameHeroMovement] = "mode-dependent"
	$g_aCurrentGameHeroes[3][$eGameHeroSourceId] = "town-hall-13-2019-12-09"
	$g_aCurrentGameHeroes[3][$eGameHeroSourceConfidence] = "official-historical-context"
	$g_aCurrentGameHeroes[3][$eGameHeroFixtureIds] = "heroes.hall.six"
	$g_aCurrentGameHeroes[3][$eGameHeroAvailabilityDate] = ""
	$g_aCurrentGameHeroes[3][$eGameHeroActiveSlotEligible] = True
	$g_aCurrentGameHeroes[4][$eGameHeroId] = "royal-champion"
	$g_aCurrentGameHeroes[4][$eGameHeroLabel] = "Royal Champion"
	$g_aCurrentGameHeroes[4][$eGameHeroUnlockTownHall] = 13
	$g_aCurrentGameHeroes[4][$eGameHeroMovement] = "ground"
	$g_aCurrentGameHeroes[4][$eGameHeroSourceId] = "town-hall-13-2019-12-09"
	$g_aCurrentGameHeroes[4][$eGameHeroSourceConfidence] = "official-explicit"
	$g_aCurrentGameHeroes[4][$eGameHeroFixtureIds] = "heroes.hall.six"
	$g_aCurrentGameHeroes[4][$eGameHeroAvailabilityDate] = ""
	$g_aCurrentGameHeroes[4][$eGameHeroActiveSlotEligible] = True
	$g_aCurrentGameHeroes[5][$eGameHeroId] = "dragon-duke"
	$g_aCurrentGameHeroes[5][$eGameHeroLabel] = "Dragon Duke"
	$g_aCurrentGameHeroes[5][$eGameHeroUnlockTownHall] = 15
	$g_aCurrentGameHeroes[5][$eGameHeroMovement] = "air"
	$g_aCurrentGameHeroes[5][$eGameHeroSourceId] = "february-2026-02-23"
	$g_aCurrentGameHeroes[5][$eGameHeroSourceConfidence] = "official-explicit"
	$g_aCurrentGameHeroes[5][$eGameHeroFixtureIds] = "heroes.dragon-duke|heroes.hall.six"
	$g_aCurrentGameHeroes[5][$eGameHeroAvailabilityDate] = "2026-03-01"
	$g_aCurrentGameHeroes[5][$eGameHeroActiveSlotEligible] = True
	$g_aCurrentGameGuardians[0][$eGameGuardianId] = "smasher"
	$g_aCurrentGameGuardians[0][$eGameGuardianLabel] = "Smasher"
	$g_aCurrentGameGuardians[0][$eGameGuardianUnlockTownHall] = 18
	$g_aCurrentGameGuardians[0][$eGameGuardianSourceId] = "town-hall-18-2025-11-17"
	$g_aCurrentGameGuardians[0][$eGameGuardianBuilderRequired] = True
	$g_aCurrentGameGuardians[0][$eGameGuardianUnavailableWhileUpgrading] = True
	$g_aCurrentGameGuardians[0][$eGameGuardianCompletedLevelDefends] = True
	$g_aCurrentGameGuardians[0][$eGameGuardianFixtureIds] = "home.th18.guardian"
	$g_aCurrentGameGuardians[1][$eGameGuardianId] = "longshot"
	$g_aCurrentGameGuardians[1][$eGameGuardianLabel] = "Longshot"
	$g_aCurrentGameGuardians[1][$eGameGuardianUnlockTownHall] = 18
	$g_aCurrentGameGuardians[1][$eGameGuardianSourceId] = "town-hall-18-2025-11-17"
	$g_aCurrentGameGuardians[1][$eGameGuardianBuilderRequired] = True
	$g_aCurrentGameGuardians[1][$eGameGuardianUnavailableWhileUpgrading] = True
	$g_aCurrentGameGuardians[1][$eGameGuardianCompletedLevelDefends] = True
	$g_aCurrentGameGuardians[1][$eGameGuardianFixtureIds] = "home.th18.guardian"
	$g_aCurrentGameGuardians[2][$eGameGuardianId] = "logger"
	$g_aCurrentGameGuardians[2][$eGameGuardianLabel] = "Logger"
	$g_aCurrentGameGuardians[2][$eGameGuardianUnlockTownHall] = 18
	$g_aCurrentGameGuardians[2][$eGameGuardianSourceId] = "sound-of-clash-2026-04-27"
	$g_aCurrentGameGuardians[2][$eGameGuardianBuilderRequired] = True
	$g_aCurrentGameGuardians[2][$eGameGuardianUnavailableWhileUpgrading] = True
	$g_aCurrentGameGuardians[2][$eGameGuardianCompletedLevelDefends] = True
	$g_aCurrentGameGuardians[2][$eGameGuardianFixtureIds] = "home.th18.guardian"
	$g_aCurrentGameBattleSurfaces[0][$eGameBattleId] = "regular"
	$g_aCurrentGameBattleSurfaces[0][$eGameBattleLabel] = "Regular Battles"
	$g_aCurrentGameBattleSurfaces[0][$eGameBattleSourceId] = "ranked-2025-10-06"
	$g_aCurrentGameBattleSurfaces[0][$eGameBattleEngineRoute] = "regular"
	$g_aCurrentGameBattleSurfaces[0][$eGameBattleParentSurface] = ""
	$g_aCurrentGameBattleSurfaces[0][$eGameBattleMinimumTownHall] = 2
	$g_aCurrentGameBattleSurfaces[0][$eGameBattleSchedule] = "continuous"
	$g_aCurrentGameBattleSurfaces[0][$eGameBattleBudgetKind] = "unlimited"
	$g_aCurrentGameBattleSurfaces[0][$eGameBattleBudgetValue] = -1
	$g_aCurrentGameBattleSurfaces[0][$eGameBattleBudgetUnit] = ""
	$g_aCurrentGameBattleSurfaces[0][$eGameBattleTrophyEffect] = "none"
	$g_aCurrentGameBattleSurfaces[0][$eGameBattleFixtureIds] = "battle.regular.entry"
	$g_aCurrentGameBattleSurfaces[0][$eGameBattleRecognitionStatus] = "fixture-required"
	$g_aCurrentGameBattleSurfaces[0][$eGameBattleExecutionStatus] = "blocked"
	$g_aCurrentGameBattleSurfaces[0][$eGameBattleLegacyFallbackAllowed] = False
	$g_aCurrentGameBattleSurfaces[0][$eGameBattleShadowBase] = False
	$g_aCurrentGameBattleSurfaces[1][$eGameBattleId] = "ranked"
	$g_aCurrentGameBattleSurfaces[1][$eGameBattleLabel] = "Ranked Battles"
	$g_aCurrentGameBattleSurfaces[1][$eGameBattleSourceId] = "ranked-2025-10-06"
	$g_aCurrentGameBattleSurfaces[1][$eGameBattleEngineRoute] = "ranked"
	$g_aCurrentGameBattleSurfaces[1][$eGameBattleParentSurface] = ""
	$g_aCurrentGameBattleSurfaces[1][$eGameBattleMinimumTownHall] = 7
	$g_aCurrentGameBattleSurfaces[1][$eGameBattleSchedule] = "weekly-tournament"
	$g_aCurrentGameBattleSurfaces[1][$eGameBattleBudgetKind] = "ui-reported"
	$g_aCurrentGameBattleSurfaces[1][$eGameBattleBudgetValue] = -1
	$g_aCurrentGameBattleSurfaces[1][$eGameBattleBudgetUnit] = "per-tournament"
	$g_aCurrentGameBattleSurfaces[1][$eGameBattleTrophyEffect] = "league-progression"
	$g_aCurrentGameBattleSurfaces[1][$eGameBattleFixtureIds] = "battle.ranked.entry"
	$g_aCurrentGameBattleSurfaces[1][$eGameBattleRecognitionStatus] = "fixture-required"
	$g_aCurrentGameBattleSurfaces[1][$eGameBattleExecutionStatus] = "blocked"
	$g_aCurrentGameBattleSurfaces[1][$eGameBattleLegacyFallbackAllowed] = False
	$g_aCurrentGameBattleSurfaces[1][$eGameBattleShadowBase] = False
	$g_aCurrentGameBattleSurfaces[2][$eGameBattleId] = "revenge"
	$g_aCurrentGameBattleSurfaces[2][$eGameBattleLabel] = "Revenge"
	$g_aCurrentGameBattleSurfaces[2][$eGameBattleSourceId] = "ranked-2025-10-06"
	$g_aCurrentGameBattleSurfaces[2][$eGameBattleEngineRoute] = ""
	$g_aCurrentGameBattleSurfaces[2][$eGameBattleParentSurface] = "regular"
	$g_aCurrentGameBattleSurfaces[2][$eGameBattleMinimumTownHall] = 2
	$g_aCurrentGameBattleSurfaces[2][$eGameBattleSchedule] = "12-hour-window"
	$g_aCurrentGameBattleSurfaces[2][$eGameBattleBudgetKind] = "single-opportunity"
	$g_aCurrentGameBattleSurfaces[2][$eGameBattleBudgetValue] = 1
	$g_aCurrentGameBattleSurfaces[2][$eGameBattleBudgetUnit] = "per-defense-log-entry"
	$g_aCurrentGameBattleSurfaces[2][$eGameBattleTrophyEffect] = "none"
	$g_aCurrentGameBattleSurfaces[2][$eGameBattleFixtureIds] = "battle.revenge.entry"
	$g_aCurrentGameBattleSurfaces[2][$eGameBattleRecognitionStatus] = "fixture-required"
	$g_aCurrentGameBattleSurfaces[2][$eGameBattleExecutionStatus] = "not-implemented"
	$g_aCurrentGameBattleSurfaces[2][$eGameBattleLegacyFallbackAllowed] = False
	$g_aCurrentGameBattleSurfaces[2][$eGameBattleShadowBase] = True
	$g_aCurrentGameBattleSurfaces[3][$eGameBattleId] = "legend-iii"
	$g_aCurrentGameBattleSurfaces[3][$eGameBattleLabel] = "Legend III"
	$g_aCurrentGameBattleSurfaces[3][$eGameBattleSourceId] = "sound-of-clash-2026-04-27"
	$g_aCurrentGameBattleSurfaces[3][$eGameBattleEngineRoute] = "legend"
	$g_aCurrentGameBattleSurfaces[3][$eGameBattleParentSurface] = "ranked"
	$g_aCurrentGameBattleSurfaces[3][$eGameBattleMinimumTownHall] = -1
	$g_aCurrentGameBattleSurfaces[3][$eGameBattleSchedule] = "weekly-tournament"
	$g_aCurrentGameBattleSurfaces[3][$eGameBattleBudgetKind] = "fixed"
	$g_aCurrentGameBattleSurfaces[3][$eGameBattleBudgetValue] = 24
	$g_aCurrentGameBattleSurfaces[3][$eGameBattleBudgetUnit] = "per-week"
	$g_aCurrentGameBattleSurfaces[3][$eGameBattleTrophyEffect] = "legend-ranking"
	$g_aCurrentGameBattleSurfaces[3][$eGameBattleFixtureIds] = "battle.legend.tier"
	$g_aCurrentGameBattleSurfaces[3][$eGameBattleRecognitionStatus] = "fixture-required"
	$g_aCurrentGameBattleSurfaces[3][$eGameBattleExecutionStatus] = "blocked"
	$g_aCurrentGameBattleSurfaces[3][$eGameBattleLegacyFallbackAllowed] = False
	$g_aCurrentGameBattleSurfaces[3][$eGameBattleShadowBase] = False
	$g_aCurrentGameBattleSurfaces[4][$eGameBattleId] = "legend-ii"
	$g_aCurrentGameBattleSurfaces[4][$eGameBattleLabel] = "Legend II"
	$g_aCurrentGameBattleSurfaces[4][$eGameBattleSourceId] = "sound-of-clash-2026-04-27"
	$g_aCurrentGameBattleSurfaces[4][$eGameBattleEngineRoute] = "legend"
	$g_aCurrentGameBattleSurfaces[4][$eGameBattleParentSurface] = "ranked"
	$g_aCurrentGameBattleSurfaces[4][$eGameBattleMinimumTownHall] = -1
	$g_aCurrentGameBattleSurfaces[4][$eGameBattleSchedule] = "weekly-tournament"
	$g_aCurrentGameBattleSurfaces[4][$eGameBattleBudgetKind] = "fixed"
	$g_aCurrentGameBattleSurfaces[4][$eGameBattleBudgetValue] = 30
	$g_aCurrentGameBattleSurfaces[4][$eGameBattleBudgetUnit] = "per-week"
	$g_aCurrentGameBattleSurfaces[4][$eGameBattleTrophyEffect] = "legend-ranking"
	$g_aCurrentGameBattleSurfaces[4][$eGameBattleFixtureIds] = "battle.legend.tier"
	$g_aCurrentGameBattleSurfaces[4][$eGameBattleRecognitionStatus] = "fixture-required"
	$g_aCurrentGameBattleSurfaces[4][$eGameBattleExecutionStatus] = "blocked"
	$g_aCurrentGameBattleSurfaces[4][$eGameBattleLegacyFallbackAllowed] = False
	$g_aCurrentGameBattleSurfaces[4][$eGameBattleShadowBase] = False
	$g_aCurrentGameBattleSurfaces[5][$eGameBattleId] = "legend-i"
	$g_aCurrentGameBattleSurfaces[5][$eGameBattleLabel] = "Legend I"
	$g_aCurrentGameBattleSurfaces[5][$eGameBattleSourceId] = "sound-of-clash-2026-04-27"
	$g_aCurrentGameBattleSurfaces[5][$eGameBattleEngineRoute] = "legend"
	$g_aCurrentGameBattleSurfaces[5][$eGameBattleParentSurface] = "ranked"
	$g_aCurrentGameBattleSurfaces[5][$eGameBattleMinimumTownHall] = -1
	$g_aCurrentGameBattleSurfaces[5][$eGameBattleSchedule] = "four-week-tournament"
	$g_aCurrentGameBattleSurfaces[5][$eGameBattleBudgetKind] = "fixed"
	$g_aCurrentGameBattleSurfaces[5][$eGameBattleBudgetValue] = 8
	$g_aCurrentGameBattleSurfaces[5][$eGameBattleBudgetUnit] = "per-league-day"
	$g_aCurrentGameBattleSurfaces[5][$eGameBattleTrophyEffect] = "legend-ranking"
	$g_aCurrentGameBattleSurfaces[5][$eGameBattleFixtureIds] = "battle.legend.tier"
	$g_aCurrentGameBattleSurfaces[5][$eGameBattleRecognitionStatus] = "fixture-required"
	$g_aCurrentGameBattleSurfaces[5][$eGameBattleExecutionStatus] = "blocked"
	$g_aCurrentGameBattleSurfaces[5][$eGameBattleLegacyFallbackAllowed] = False
	$g_aCurrentGameBattleSurfaces[5][$eGameBattleShadowBase] = False
	$g_aCurrentGameBattleSurfaces[6][$eGameBattleId] = "builder"
	$g_aCurrentGameBattleSurfaces[6][$eGameBattleLabel] = "Builder Base Battles"
	$g_aCurrentGameBattleSurfaces[6][$eGameBattleSourceId] = "may-update-2026-05-26"
	$g_aCurrentGameBattleSurfaces[6][$eGameBattleEngineRoute] = "builder"
	$g_aCurrentGameBattleSurfaces[6][$eGameBattleParentSurface] = ""
	$g_aCurrentGameBattleSurfaces[6][$eGameBattleMinimumTownHall] = -1
	$g_aCurrentGameBattleSurfaces[6][$eGameBattleSchedule] = "continuous"
	$g_aCurrentGameBattleSurfaces[6][$eGameBattleBudgetKind] = "ui-reported"
	$g_aCurrentGameBattleSurfaces[6][$eGameBattleBudgetValue] = -1
	$g_aCurrentGameBattleSurfaces[6][$eGameBattleBudgetUnit] = ""
	$g_aCurrentGameBattleSurfaces[6][$eGameBattleTrophyEffect] = "builder-ranking"
	$g_aCurrentGameBattleSurfaces[6][$eGameBattleFixtureIds] = "builder.battle.entry"
	$g_aCurrentGameBattleSurfaces[6][$eGameBattleRecognitionStatus] = "fixture-required"
	$g_aCurrentGameBattleSurfaces[6][$eGameBattleExecutionStatus] = "blocked"
	$g_aCurrentGameBattleSurfaces[6][$eGameBattleLegacyFallbackAllowed] = False
	$g_aCurrentGameBattleSurfaces[6][$eGameBattleShadowBase] = False
	$g_aCurrentGameScreenStates[0][$eGameScreenId] = "army.recipes.home"
	$g_aCurrentGameScreenStates[0][$eGameScreenCategory] = "army"
	$g_aCurrentGameScreenStates[0][$eGameScreenSourceId] = "clash-anytime-2025-03-24"
	$g_aCurrentGameScreenStates[0][$eGameScreenCapabilityIds] = "army.recipes"
	$g_aCurrentGameScreenStates[0][$eGameScreenFixtureIds] = "army.recipes.home"
	$g_aCurrentGameScreenStates[0][$eGameScreenBlocking] = False
	$g_aCurrentGameScreenStates[0][$eGameScreenRecognitionStatus] = "fixture-required"
	$g_aCurrentGameScreenStates[0][$eGameScreenHandlerStatus] = "not-implemented"
	$g_aCurrentGameScreenStates[0][$eGameScreenSafeDefaultAction] = "observe"
	$g_aCurrentGameScreenStates[0][$eGameScreenRetryLimit] = 0
	$g_aCurrentGameScreenStates[0][$eGameScreenAppearsAfterSeconds] = -1
	$g_aCurrentGameScreenStates[0][$eGameScreenSpeedMultiplier] = -1
	$g_aCurrentGameScreenStates[1][$eGameScreenId] = "army.cookbook.tab"
	$g_aCurrentGameScreenStates[1][$eGameScreenCategory] = "army"
	$g_aCurrentGameScreenStates[1][$eGameScreenSourceId] = "lets-get-crafty-2025-06-16"
	$g_aCurrentGameScreenStates[1][$eGameScreenCapabilityIds] = "army.cookbook"
	$g_aCurrentGameScreenStates[1][$eGameScreenFixtureIds] = "army.cookbook.tab"
	$g_aCurrentGameScreenStates[1][$eGameScreenBlocking] = False
	$g_aCurrentGameScreenStates[1][$eGameScreenRecognitionStatus] = "fixture-required"
	$g_aCurrentGameScreenStates[1][$eGameScreenHandlerStatus] = "not-implemented"
	$g_aCurrentGameScreenStates[1][$eGameScreenSafeDefaultAction] = "observe"
	$g_aCurrentGameScreenStates[1][$eGameScreenRetryLimit] = 0
	$g_aCurrentGameScreenStates[1][$eGameScreenAppearsAfterSeconds] = -1
	$g_aCurrentGameScreenStates[1][$eGameScreenSpeedMultiplier] = -1
	$g_aCurrentGameScreenStates[2][$eGameScreenId] = "defense.crafted.management"
	$g_aCurrentGameScreenStates[2][$eGameScreenCategory] = "village"
	$g_aCurrentGameScreenStates[2][$eGameScreenSourceId] = "lets-get-crafty-2025-06-16"
	$g_aCurrentGameScreenStates[2][$eGameScreenCapabilityIds] = "defense.crafted"
	$g_aCurrentGameScreenStates[2][$eGameScreenFixtureIds] = "defense.crafted.management"
	$g_aCurrentGameScreenStates[2][$eGameScreenBlocking] = False
	$g_aCurrentGameScreenStates[2][$eGameScreenRecognitionStatus] = "fixture-required"
	$g_aCurrentGameScreenStates[2][$eGameScreenHandlerStatus] = "not-implemented"
	$g_aCurrentGameScreenStates[2][$eGameScreenSafeDefaultAction] = "observe"
	$g_aCurrentGameScreenStates[2][$eGameScreenRetryLimit] = 0
	$g_aCurrentGameScreenStates[2][$eGameScreenAppearsAfterSeconds] = -1
	$g_aCurrentGameScreenStates[2][$eGameScreenSpeedMultiplier] = -1
	$g_aCurrentGameScreenStates[3][$eGameScreenId] = "battle.regular.entry"
	$g_aCurrentGameScreenStates[3][$eGameScreenCategory] = "battle"
	$g_aCurrentGameScreenStates[3][$eGameScreenSourceId] = "ranked-2025-10-06"
	$g_aCurrentGameScreenStates[3][$eGameScreenCapabilityIds] = "battle.regular-ranked-split"
	$g_aCurrentGameScreenStates[3][$eGameScreenFixtureIds] = "battle.regular.entry"
	$g_aCurrentGameScreenStates[3][$eGameScreenBlocking] = True
	$g_aCurrentGameScreenStates[3][$eGameScreenRecognitionStatus] = "fixture-required"
	$g_aCurrentGameScreenStates[3][$eGameScreenHandlerStatus] = "not-implemented"
	$g_aCurrentGameScreenStates[3][$eGameScreenSafeDefaultAction] = "stop-route"
	$g_aCurrentGameScreenStates[3][$eGameScreenRetryLimit] = 1
	$g_aCurrentGameScreenStates[3][$eGameScreenAppearsAfterSeconds] = -1
	$g_aCurrentGameScreenStates[3][$eGameScreenSpeedMultiplier] = -1
	$g_aCurrentGameScreenStates[4][$eGameScreenId] = "battle.ranked.entry"
	$g_aCurrentGameScreenStates[4][$eGameScreenCategory] = "battle"
	$g_aCurrentGameScreenStates[4][$eGameScreenSourceId] = "ranked-2025-10-06"
	$g_aCurrentGameScreenStates[4][$eGameScreenCapabilityIds] = "battle.regular-ranked-split"
	$g_aCurrentGameScreenStates[4][$eGameScreenFixtureIds] = "battle.ranked.entry"
	$g_aCurrentGameScreenStates[4][$eGameScreenBlocking] = True
	$g_aCurrentGameScreenStates[4][$eGameScreenRecognitionStatus] = "fixture-required"
	$g_aCurrentGameScreenStates[4][$eGameScreenHandlerStatus] = "not-implemented"
	$g_aCurrentGameScreenStates[4][$eGameScreenSafeDefaultAction] = "stop-route"
	$g_aCurrentGameScreenStates[4][$eGameScreenRetryLimit] = 1
	$g_aCurrentGameScreenStates[4][$eGameScreenAppearsAfterSeconds] = -1
	$g_aCurrentGameScreenStates[4][$eGameScreenSpeedMultiplier] = -1
	$g_aCurrentGameScreenStates[5][$eGameScreenId] = "battle.revenge.entry"
	$g_aCurrentGameScreenStates[5][$eGameScreenCategory] = "battle"
	$g_aCurrentGameScreenStates[5][$eGameScreenSourceId] = "ranked-2025-10-06"
	$g_aCurrentGameScreenStates[5][$eGameScreenCapabilityIds] = "battle.revenge"
	$g_aCurrentGameScreenStates[5][$eGameScreenFixtureIds] = "battle.revenge.entry"
	$g_aCurrentGameScreenStates[5][$eGameScreenBlocking] = True
	$g_aCurrentGameScreenStates[5][$eGameScreenRecognitionStatus] = "fixture-required"
	$g_aCurrentGameScreenStates[5][$eGameScreenHandlerStatus] = "not-implemented"
	$g_aCurrentGameScreenStates[5][$eGameScreenSafeDefaultAction] = "stop-route"
	$g_aCurrentGameScreenStates[5][$eGameScreenRetryLimit] = 0
	$g_aCurrentGameScreenStates[5][$eGameScreenAppearsAfterSeconds] = -1
	$g_aCurrentGameScreenStates[5][$eGameScreenSpeedMultiplier] = -1
	$g_aCurrentGameScreenStates[6][$eGameScreenId] = "battle.legend.tier"
	$g_aCurrentGameScreenStates[6][$eGameScreenCategory] = "battle"
	$g_aCurrentGameScreenStates[6][$eGameScreenSourceId] = "sound-of-clash-2026-04-27"
	$g_aCurrentGameScreenStates[6][$eGameScreenCapabilityIds] = "battle.legend-tiers"
	$g_aCurrentGameScreenStates[6][$eGameScreenFixtureIds] = "battle.legend.tier"
	$g_aCurrentGameScreenStates[6][$eGameScreenBlocking] = True
	$g_aCurrentGameScreenStates[6][$eGameScreenRecognitionStatus] = "fixture-required"
	$g_aCurrentGameScreenStates[6][$eGameScreenHandlerStatus] = "not-implemented"
	$g_aCurrentGameScreenStates[6][$eGameScreenSafeDefaultAction] = "stop-route"
	$g_aCurrentGameScreenStates[6][$eGameScreenRetryLimit] = 1
	$g_aCurrentGameScreenStates[6][$eGameScreenAppearsAfterSeconds] = -1
	$g_aCurrentGameScreenStates[6][$eGameScreenSpeedMultiplier] = -1
	$g_aCurrentGameScreenStates[7][$eGameScreenId] = "battle.fast-forward"
	$g_aCurrentGameScreenStates[7][$eGameScreenCategory] = "battle"
	$g_aCurrentGameScreenStates[7][$eGameScreenSourceId] = "anime-fury-2026-06-15"
	$g_aCurrentGameScreenStates[7][$eGameScreenCapabilityIds] = "battle.fast-forward"
	$g_aCurrentGameScreenStates[7][$eGameScreenFixtureIds] = "battle.fast-forward"
	$g_aCurrentGameScreenStates[7][$eGameScreenBlocking] = False
	$g_aCurrentGameScreenStates[7][$eGameScreenRecognitionStatus] = "fixture-required"
	$g_aCurrentGameScreenStates[7][$eGameScreenHandlerStatus] = "not-implemented"
	$g_aCurrentGameScreenStates[7][$eGameScreenSafeDefaultAction] = "ignore"
	$g_aCurrentGameScreenStates[7][$eGameScreenRetryLimit] = 0
	$g_aCurrentGameScreenStates[7][$eGameScreenAppearsAfterSeconds] = 120
	$g_aCurrentGameScreenStates[7][$eGameScreenSpeedMultiplier] = 4
	$g_aCurrentGameScreenStates[8][$eGameScreenId] = "village.town-hall-18"
	$g_aCurrentGameScreenStates[8][$eGameScreenCategory] = "village"
	$g_aCurrentGameScreenStates[8][$eGameScreenSourceId] = "town-hall-18-2025-11-17"
	$g_aCurrentGameScreenStates[8][$eGameScreenCapabilityIds] = "village.town-hall-18"
	$g_aCurrentGameScreenStates[8][$eGameScreenFixtureIds] = "home.th18.default"
	$g_aCurrentGameScreenStates[8][$eGameScreenBlocking] = False
	$g_aCurrentGameScreenStates[8][$eGameScreenRecognitionStatus] = "fixture-required"
	$g_aCurrentGameScreenStates[8][$eGameScreenHandlerStatus] = "not-implemented"
	$g_aCurrentGameScreenStates[8][$eGameScreenSafeDefaultAction] = "observe"
	$g_aCurrentGameScreenStates[8][$eGameScreenRetryLimit] = 0
	$g_aCurrentGameScreenStates[8][$eGameScreenAppearsAfterSeconds] = -1
	$g_aCurrentGameScreenStates[8][$eGameScreenSpeedMultiplier] = -1
	$g_aCurrentGameScreenStates[9][$eGameScreenId] = "village.guardian.management"
	$g_aCurrentGameScreenStates[9][$eGameScreenCategory] = "village"
	$g_aCurrentGameScreenStates[9][$eGameScreenSourceId] = "town-hall-18-2025-11-17"
	$g_aCurrentGameScreenStates[9][$eGameScreenCapabilityIds] = "village.guardians"
	$g_aCurrentGameScreenStates[9][$eGameScreenFixtureIds] = "home.th18.guardian"
	$g_aCurrentGameScreenStates[9][$eGameScreenBlocking] = False
	$g_aCurrentGameScreenStates[9][$eGameScreenRecognitionStatus] = "fixture-required"
	$g_aCurrentGameScreenStates[9][$eGameScreenHandlerStatus] = "not-implemented"
	$g_aCurrentGameScreenStates[9][$eGameScreenSafeDefaultAction] = "observe"
	$g_aCurrentGameScreenStates[9][$eGameScreenRetryLimit] = 0
	$g_aCurrentGameScreenStates[9][$eGameScreenAppearsAfterSeconds] = -1
	$g_aCurrentGameScreenStates[9][$eGameScreenSpeedMultiplier] = -1
	$g_aCurrentGameScreenStates[10][$eGameScreenId] = "heroes.hall.six"
	$g_aCurrentGameScreenStates[10][$eGameScreenCategory] = "heroes"
	$g_aCurrentGameScreenStates[10][$eGameScreenSourceId] = "february-2026-02-23"
	$g_aCurrentGameScreenStates[10][$eGameScreenCapabilityIds] = "heroes.six-slot-layout"
	$g_aCurrentGameScreenStates[10][$eGameScreenFixtureIds] = "heroes.hall.six"
	$g_aCurrentGameScreenStates[10][$eGameScreenBlocking] = False
	$g_aCurrentGameScreenStates[10][$eGameScreenRecognitionStatus] = "fixture-required"
	$g_aCurrentGameScreenStates[10][$eGameScreenHandlerStatus] = "not-implemented"
	$g_aCurrentGameScreenStates[10][$eGameScreenSafeDefaultAction] = "observe"
	$g_aCurrentGameScreenStates[10][$eGameScreenRetryLimit] = 0
	$g_aCurrentGameScreenStates[10][$eGameScreenAppearsAfterSeconds] = -1
	$g_aCurrentGameScreenStates[10][$eGameScreenSpeedMultiplier] = -1
	$g_aCurrentGameScreenStates[11][$eGameScreenId] = "heroes.dragon-duke"
	$g_aCurrentGameScreenStates[11][$eGameScreenCategory] = "heroes"
	$g_aCurrentGameScreenStates[11][$eGameScreenSourceId] = "february-2026-02-23"
	$g_aCurrentGameScreenStates[11][$eGameScreenCapabilityIds] = "heroes.dragon-duke"
	$g_aCurrentGameScreenStates[11][$eGameScreenFixtureIds] = "heroes.dragon-duke"
	$g_aCurrentGameScreenStates[11][$eGameScreenBlocking] = False
	$g_aCurrentGameScreenStates[11][$eGameScreenRecognitionStatus] = "fixture-required"
	$g_aCurrentGameScreenStates[11][$eGameScreenHandlerStatus] = "not-implemented"
	$g_aCurrentGameScreenStates[11][$eGameScreenSafeDefaultAction] = "observe"
	$g_aCurrentGameScreenStates[11][$eGameScreenRetryLimit] = 0
	$g_aCurrentGameScreenStates[11][$eGameScreenAppearsAfterSeconds] = -1
	$g_aCurrentGameScreenStates[11][$eGameScreenSpeedMultiplier] = -1
	$g_aCurrentGameScreenStates[12][$eGameScreenId] = "heroes.journey"
	$g_aCurrentGameScreenStates[12][$eGameScreenCategory] = "heroes"
	$g_aCurrentGameScreenStates[12][$eGameScreenSourceId] = "anime-fury-2026-06-15"
	$g_aCurrentGameScreenStates[12][$eGameScreenCapabilityIds] = "heroes.hero-journey"
	$g_aCurrentGameScreenStates[12][$eGameScreenFixtureIds] = "heroes.journey.interruption"
	$g_aCurrentGameScreenStates[12][$eGameScreenBlocking] = True
	$g_aCurrentGameScreenStates[12][$eGameScreenRecognitionStatus] = "fixture-required"
	$g_aCurrentGameScreenStates[12][$eGameScreenHandlerStatus] = "not-implemented"
	$g_aCurrentGameScreenStates[12][$eGameScreenSafeDefaultAction] = "stop-route"
	$g_aCurrentGameScreenStates[12][$eGameScreenRetryLimit] = 1
	$g_aCurrentGameScreenStates[12][$eGameScreenAppearsAfterSeconds] = -1
	$g_aCurrentGameScreenStates[12][$eGameScreenSpeedMultiplier] = -1
	$g_aCurrentGameScreenStates[13][$eGameScreenId] = "chat.global.closed"
	$g_aCurrentGameScreenStates[13][$eGameScreenCategory] = "chat"
	$g_aCurrentGameScreenStates[13][$eGameScreenSourceId] = "anime-fury-2026-06-15"
	$g_aCurrentGameScreenStates[13][$eGameScreenCapabilityIds] = "chat.global-chat"
	$g_aCurrentGameScreenStates[13][$eGameScreenFixtureIds] = "chat.global.closed"
	$g_aCurrentGameScreenStates[13][$eGameScreenBlocking] = False
	$g_aCurrentGameScreenStates[13][$eGameScreenRecognitionStatus] = "fixture-required"
	$g_aCurrentGameScreenStates[13][$eGameScreenHandlerStatus] = "not-implemented"
	$g_aCurrentGameScreenStates[13][$eGameScreenSafeDefaultAction] = "ignore"
	$g_aCurrentGameScreenStates[13][$eGameScreenRetryLimit] = 0
	$g_aCurrentGameScreenStates[13][$eGameScreenAppearsAfterSeconds] = -1
	$g_aCurrentGameScreenStates[13][$eGameScreenSpeedMultiplier] = -1
	$g_aCurrentGameScreenStates[14][$eGameScreenId] = "chat.global.open"
	$g_aCurrentGameScreenStates[14][$eGameScreenCategory] = "chat"
	$g_aCurrentGameScreenStates[14][$eGameScreenSourceId] = "anime-fury-2026-06-15"
	$g_aCurrentGameScreenStates[14][$eGameScreenCapabilityIds] = "chat.global-chat"
	$g_aCurrentGameScreenStates[14][$eGameScreenFixtureIds] = "chat.global.open"
	$g_aCurrentGameScreenStates[14][$eGameScreenBlocking] = True
	$g_aCurrentGameScreenStates[14][$eGameScreenRecognitionStatus] = "fixture-required"
	$g_aCurrentGameScreenStates[14][$eGameScreenHandlerStatus] = "not-implemented"
	$g_aCurrentGameScreenStates[14][$eGameScreenSafeDefaultAction] = "stop-route"
	$g_aCurrentGameScreenStates[14][$eGameScreenRetryLimit] = 1
	$g_aCurrentGameScreenStates[14][$eGameScreenAppearsAfterSeconds] = -1
	$g_aCurrentGameScreenStates[14][$eGameScreenSpeedMultiplier] = -1
	$g_aCurrentGameScreenStates[15][$eGameScreenId] = "builder.extra-builder.shop"
	$g_aCurrentGameScreenStates[15][$eGameScreenCategory] = "builder-base"
	$g_aCurrentGameScreenStates[15][$eGameScreenSourceId] = "may-update-2026-05-26"
	$g_aCurrentGameScreenStates[15][$eGameScreenCapabilityIds] = "builder-base.additional-builder"
	$g_aCurrentGameScreenStates[15][$eGameScreenFixtureIds] = "builder.home.extra-builder"
	$g_aCurrentGameScreenStates[15][$eGameScreenBlocking] = False
	$g_aCurrentGameScreenStates[15][$eGameScreenRecognitionStatus] = "fixture-required"
	$g_aCurrentGameScreenStates[15][$eGameScreenHandlerStatus] = "not-implemented"
	$g_aCurrentGameScreenStates[15][$eGameScreenSafeDefaultAction] = "ignore"
	$g_aCurrentGameScreenStates[15][$eGameScreenRetryLimit] = 0
	$g_aCurrentGameScreenStates[15][$eGameScreenAppearsAfterSeconds] = -1
	$g_aCurrentGameScreenStates[15][$eGameScreenSpeedMultiplier] = -1
	$g_aCurrentGameScreenStates[16][$eGameScreenId] = "shop.chain-offers"
	$g_aCurrentGameScreenStates[16][$eGameScreenCategory] = "shop"
	$g_aCurrentGameScreenStates[16][$eGameScreenSourceId] = "anime-fury-2026-06-15"
	$g_aCurrentGameScreenStates[16][$eGameScreenCapabilityIds] = "shop.chain-offers"
	$g_aCurrentGameScreenStates[16][$eGameScreenFixtureIds] = "shop.chain-offers"
	$g_aCurrentGameScreenStates[16][$eGameScreenBlocking] = False
	$g_aCurrentGameScreenStates[16][$eGameScreenRecognitionStatus] = "fixture-required"
	$g_aCurrentGameScreenStates[16][$eGameScreenHandlerStatus] = "not-implemented"
	$g_aCurrentGameScreenStates[16][$eGameScreenSafeDefaultAction] = "ignore"
	$g_aCurrentGameScreenStates[16][$eGameScreenRetryLimit] = 0
	$g_aCurrentGameScreenStates[16][$eGameScreenAppearsAfterSeconds] = -1
	$g_aCurrentGameScreenStates[16][$eGameScreenSpeedMultiplier] = -1
	$__g_bCurrentGameCatalogInitialized = True
EndFunc   ;==>_InitializeCurrentGameCatalogGenerated

_InitializeCurrentGameCatalogGenerated()
