#!/usr/bin/env python3
"""Turn the Run Planner metadata into an AutoIt table.

The GUI renders from this table instead of a hand-written layout, so adding a battle surface or changing a
disabled reason is a catalog edit rather than a GUI edit. Output is deterministic; CI checks it for drift.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SETTINGS_PATH = ROOT / "config/ui/run-planner.settings.json"
DEFAULT_OUT = ROOT / "COCBot/GUI/RunPlannerMetadata.generated.au3"

HEADER = """; #FUNCTION# ====================================================================================================================
; Name ..........: Run Planner metadata
; Description ...: Generated descriptor for the Run Planner tab.
; Remarks .......: Generated by tools/generate_run_planner_autoit.py from config/ui/run-planner.settings.json.
;                  Do not edit by hand; regenerate instead. CI fails if this file drifts from the source metadata.
; ===============================================================================================================================
#include-once

Global Const $RUN_PLANNER_SCHEMA_VERSION = {schema_version}
Global Const $RUN_PLANNER_TITLE = {title}
Global Const $RUN_PLANNER_DESCRIPTION = {description}

Global Enum $eRunPlannerSectionId, $eRunPlannerSectionOrder, $eRunPlannerSectionTitle, $eRunPlannerSectionTabLabel, $eRunPlannerSectionDescription, $eRunPlannerSectionColumnCount
Global Enum $eRunPlannerSettingId, $eRunPlannerSettingSectionId, $eRunPlannerSettingType, $eRunPlannerSettingLabel, $eRunPlannerSettingSummary, $eRunPlannerSettingDescription, $eRunPlannerSettingDefault, $eRunPlannerSettingRequired, $eRunPlannerSettingBinding, $eRunPlannerSettingUnit, $eRunPlannerSettingMinimum, $eRunPlannerSettingMaximum, $eRunPlannerSettingStep, $eRunPlannerSettingEmptyState, $eRunPlannerSettingNativeFixed, $eRunPlannerSettingNativeFixedValue, $eRunPlannerSettingNativeFixedReason, $eRunPlannerSettingColumnCount
Global Enum $eRunPlannerOptionSettingId, $eRunPlannerOptionValue, $eRunPlannerOptionLabel, $eRunPlannerOptionSummary, $eRunPlannerOptionDescription, $eRunPlannerOptionAvailability, $eRunPlannerOptionDisabledReason, $eRunPlannerOptionPrerequisites, $eRunPlannerOptionCapabilityIds, $eRunPlannerOptionRecommended, $eRunPlannerOptionWarning, $eRunPlannerOptionColumnCount

Global $g_aRunPlannerSections[{section_count}][$eRunPlannerSectionColumnCount]
Global $g_aRunPlannerSettings[{setting_count}][$eRunPlannerSettingColumnCount]
Global $g_aRunPlannerOptions[{option_count}][$eRunPlannerOptionColumnCount]

Func _RunPlannerMetadataInit()
"""

FOOTER = """EndFunc   ;==>_RunPlannerMetadataInit

_RunPlannerMetadataInit()
"""


def au3_string(value) -> str:
    """AutoIt escapes a double quote by doubling it; there is no backslash escape."""
    text = "" if value is None else str(value)
    return '"' + text.replace('"', '""') + '"'


def au3_bool(value) -> str:
    return "True" if value else "False"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path, default=DEFAULT_OUT)
    parser.add_argument("--check", action="store_true", help="fail if the output would change")
    args = parser.parse_args()

    settings_doc = json.loads(SETTINGS_PATH.read_text(encoding="utf-8-sig"))
    sections = sorted(settings_doc["sections"], key=lambda s: s["order"])

    flat_settings = []
    flat_options = []
    for section in sections:
        for setting in section["settings"]:
            flat_settings.append((section["id"], setting))
            for opt in setting.get("options", []):
                flat_options.append((setting["id"], opt))

    body = []
    for index, section in enumerate(sections):
        body.append(f'\t$g_aRunPlannerSections[{index}][$eRunPlannerSectionId] = {au3_string(section["id"])}')
        body.append(f'\t$g_aRunPlannerSections[{index}][$eRunPlannerSectionOrder] = {int(section["order"])}')
        body.append(f'\t$g_aRunPlannerSections[{index}][$eRunPlannerSectionTitle] = {au3_string(section["title"])}')
        body.append(f'\t$g_aRunPlannerSections[{index}][$eRunPlannerSectionTabLabel] = {au3_string(section["tab_label"])}')
        body.append(
            f'\t$g_aRunPlannerSections[{index}][$eRunPlannerSectionDescription] = {au3_string(section["description"])}'
        )

    for index, (section_id, setting) in enumerate(flat_settings):
        validation = setting.get("validation", {})
        native_fixed = "native_fixed_value" in setting
        native_fixed_value = setting.get("native_fixed_value", "")
        if isinstance(native_fixed_value, bool):
            native_fixed_literal = au3_bool(native_fixed_value)
        elif isinstance(native_fixed_value, int):
            native_fixed_literal = str(native_fixed_value)
        else:
            native_fixed_literal = au3_string(native_fixed_value)
        pairs = [
            ("Id", au3_string(setting["id"])),
            ("SectionId", au3_string(section_id)),
            ("Type", au3_string(setting["type"])),
            ("Label", au3_string(setting["label"])),
            ("Summary", au3_string(setting["summary"])),
            ("Description", au3_string(setting["description"])),
            ("Default", au3_bool(setting["default"]) if isinstance(setting["default"], bool) else (
                str(setting["default"]) if isinstance(setting["default"], int) else au3_string(setting["default"]))),
            ("Required", au3_bool(setting.get("required", False))),
            ("Binding", au3_string(setting["engine_binding"])),
            ("Unit", au3_string(setting.get("unit", ""))),
            ("Minimum", str(int(validation.get("minimum", 0)))),
            ("Maximum", str(int(validation.get("maximum", 0)))),
            ("Step", str(int(validation.get("step", 0)))),
            ("EmptyState", au3_string(setting.get("empty_state", ""))),
            ("NativeFixed", au3_bool(native_fixed)),
            ("NativeFixedValue", native_fixed_literal),
            ("NativeFixedReason", au3_string(setting.get("native_fixed_reason", ""))),
        ]
        for name, value in pairs:
            body.append(f"\t$g_aRunPlannerSettings[{index}][$eRunPlannerSetting{name}] = {value}")

    for index, (setting_id, opt) in enumerate(flat_options):
        pairs = [
            ("SettingId", au3_string(setting_id)),
            ("Value", au3_string(opt["value"])),
            ("Label", au3_string(opt["label"])),
            ("Summary", au3_string(opt["summary"])),
            ("Description", au3_string(opt["description"])),
            ("Availability", au3_string(opt["availability"])),
            ("DisabledReason", au3_string(opt.get("disabled_reason", ""))),
            ("Prerequisites", au3_string("|".join(opt.get("prerequisites", [])))),
            ("CapabilityIds", au3_string("|".join(opt.get("capability_ids", [])))),
            ("Recommended", au3_bool(opt.get("recommended", False))),
            ("Warning", au3_string(opt.get("warning", ""))),
        ]
        for name, value in pairs:
            body.append(f"\t$g_aRunPlannerOptions[{index}][$eRunPlannerOption{name}] = {value}")

    rendered = HEADER.format(
        schema_version=int(settings_doc["schema_version"]),
        title=au3_string(settings_doc["title"]),
        description=au3_string(settings_doc["description"]),
        section_count=len(sections),
        setting_count=len(flat_settings),
        option_count=len(flat_options),
    ) + "\n".join(body) + "\n" + FOOTER

    if args.check:
        current = args.output.read_text(encoding="utf-8") if args.output.exists() else ""
        if current != rendered:
            print(f"{args.output.relative_to(ROOT)} is out of date; run tools/generate_run_planner_autoit.py")
            return 1
        print(f"{args.output.relative_to(ROOT)} is current")
        return 0

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(rendered, encoding="utf-8")
    print(
        f"Wrote {args.output.relative_to(ROOT)} with {len(sections)} sections, "
        f"{len(flat_settings)} settings, {len(flat_options)} options"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
