#!/usr/bin/env python3
"""Generate the inert native clean-room recognition contract.

The generated file contains only bounded constants and exact fixture hashes.  It
does not serialize legacy DLL calls, expose file paths, or authorize game input.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
MANIFEST_PATH = ROOT / "config" / "cleanroom-recognition.json"
DEFAULT_OUT = ROOT / "COCBot" / "functions" / "Run" / "CleanRoomRecognitionContract.generated.au3"


def _au3_string(value: object) -> str:
    return '"' + str(value).replace('"', '""') + '"'


def _require(condition: bool, message: str) -> None:
    if not condition:
        raise ValueError(message)


def render_contract(document: dict[str, object]) -> str:
    _require(document.get("schema_version") == 1, "unsupported clean-room recognition schema")
    adapter_id = document.get("adapter_id")
    _require(isinstance(adapter_id, str) and adapter_id, "adapter_id is required")

    runtime = document.get("runtime_bridge")
    _require(isinstance(runtime, dict), "runtime_bridge is required")
    expected_runtime = {
        "contract_path": "COCBot/functions/Run/CleanRoomRecognitionContract.generated.au3",
        "bridge_path": "COCBot/functions/Run/CleanRoomRecognitionBridge.au3",
        "mode": "read-only",
        "legacy_dispatch_wired": False,
        "bot_start_wired": False,
        "find_tile_behavior": "verified-fixture-attestation-only-no-coordinate",
        "python_adapter_packaged": False,
    }
    _require(runtime == expected_runtime, "runtime_bridge must remain the exact inert read-only contract")

    limits = document.get("limits")
    _require(isinstance(limits, dict), "limits are required")
    for key in ("max_width", "max_height", "max_pixels", "max_results", "max_points"):
        _require(type(limits.get(key)) is int and int(limits[key]) > 0, f"invalid limit: {key}")

    exports = document.get("legacy_exports")
    _require(isinstance(exports, list) and len(exports) == 17, "exactly 17 exports are required")
    names = [item.get("name") for item in exports if isinstance(item, dict)]
    _require(len(names) == 17 and len(set(names)) == 17, "export names must be unique")
    implemented = [item for item in exports if isinstance(item, dict) and item.get("clean_room_status") == "implemented"]
    _require(
        {item.get("name") for item in implemented} == {"FindTile", "GetDeployableNextTo", "GetOffSetRedline"},
        "only the reviewed three-export tranche may be implemented",
    )
    unavailable = [item for item in exports if isinstance(item, dict) and item.get("clean_room_status") == "unavailable"]
    _require(len(unavailable) == 14, "exactly 14 exports must remain unavailable")
    _require(all(isinstance(item.get("unavailable_reason"), str) and item["unavailable_reason"] for item in unavailable), "every unavailable export needs a reason")

    assets = document.get("assets")
    _require(isinstance(assets, dict) and set(assets) == {"current-client.daily-reward.claim"}, "the fixture replay asset set must remain closed")
    asset = assets["current-client.daily-reward.claim"]
    _require(isinstance(asset, dict), "fixture replay asset is malformed")
    _require(asset.get("export") == "FindTile", "fixture replay asset must bind FindTile")
    _require(asset.get("evidence_scope") == "verified-fixture-replay-only", "FindTile must remain fixture replay only")
    _require(asset.get("live_tolerance_proven") is False, "FindTile live tolerance must remain unproven")
    _require(asset.get("bot_start_wired") is False, "FindTile must remain outside BotStart")
    _require(asset.get("legacy_wire_compatible") is False, "FindTile must remain legacy-wire incompatible")
    size = asset.get("required_screenshot_size")
    _require(isinstance(size, list) and len(size) == 2 and all(type(value) is int and value > 0 for value in size), "fixture dimensions are invalid")
    for key in ("fixture_id", "image_sha256", "metadata_sha256"):
        _require(isinstance(asset.get(key), str) and asset[key], f"fixture field is missing: {key}")

    unavailable_names = "|".join(str(item["name"]) for item in unavailable)
    lines = [
        "; #FUNCTION# ====================================================================================================================",
        "; Name ..........: Clean-room recognition contract",
        "; Description ...: Generated constants for an inert, read-only native recognition bridge.",
        "; Remarks .......: Generated by tools/generate_cleanroom_recognition_autoit.py from config/cleanroom-recognition.json.",
        ";                  Do not edit by hand. This contract never authorizes input or legacy DLL dispatch.",
        "; ===============================================================================================================================",
        "#include-once",
        "",
        f"Global Const $CLEANROOM_RECOGNITION_SCHEMA_VERSION = {int(document['schema_version'])}",
        f"Global Const $CLEANROOM_RECOGNITION_ADAPTER_ID = {_au3_string(adapter_id)}",
        "Global Const $CLEANROOM_RECOGNITION_EXPORT_COUNT = 17",
        "Global Const $CLEANROOM_RECOGNITION_STATUS_READ_ONLY_PURE = \"READ_ONLY_PURE\"",
        "Global Const $CLEANROOM_RECOGNITION_STATUS_FIXTURE_REPLAY_ONLY = \"FIXTURE_REPLAY_ONLY\"",
        "Global Const $CLEANROOM_RECOGNITION_STATUS_UNAVAILABLE = \"UNAVAILABLE\"",
        "Global Const $CLEANROOM_RECOGNITION_STATUS_REJECTED = \"REJECTED\"",
        f"Global Const $CLEANROOM_RECOGNITION_UNAVAILABLE_EXPORTS = {_au3_string(unavailable_names)}",
        f"Global Const $CLEANROOM_RECOGNITION_MAX_WIDTH = {int(limits['max_width'])}",
        f"Global Const $CLEANROOM_RECOGNITION_MAX_HEIGHT = {int(limits['max_height'])}",
        f"Global Const $CLEANROOM_RECOGNITION_MAX_PIXELS = {int(limits['max_pixels'])}",
        f"Global Const $CLEANROOM_RECOGNITION_MAX_RESULTS = {int(limits['max_results'])}",
        f"Global Const $CLEANROOM_RECOGNITION_MAX_POINTS = {int(limits['max_points'])}",
        f"Global Const $CLEANROOM_RECOGNITION_FIXTURE_ASSET_ID = {_au3_string('current-client.daily-reward.claim')}",
        f"Global Const $CLEANROOM_RECOGNITION_FIXTURE_ID = {_au3_string(asset['fixture_id'])}",
        f"Global Const $CLEANROOM_RECOGNITION_FIXTURE_IMAGE_SHA256 = {_au3_string(asset['image_sha256'])}",
        f"Global Const $CLEANROOM_RECOGNITION_FIXTURE_METADATA_SHA256 = {_au3_string(asset['metadata_sha256'])}",
        f"Global Const $CLEANROOM_RECOGNITION_FIXTURE_WIDTH = {int(size[0])}",
        f"Global Const $CLEANROOM_RECOGNITION_FIXTURE_HEIGHT = {int(size[1])}",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path, default=DEFAULT_OUT)
    parser.add_argument("--check", action="store_true", help="fail if the generated contract would change")
    args = parser.parse_args()
    document = json.loads(MANIFEST_PATH.read_text(encoding="utf-8"))
    rendered = render_contract(document)
    if args.check:
        current = args.output.read_text(encoding="utf-8") if args.output.exists() else ""
        if current != rendered:
            print(f"{args.output.relative_to(ROOT)} is out of date; run tools/generate_cleanroom_recognition_autoit.py")
            return 1
        print(f"{args.output.relative_to(ROOT)} is current")
        return 0
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(rendered, encoding="utf-8")
    print(f"Wrote {args.output.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
