; #FUNCTION# ====================================================================================================================
; Name ..........: Clean-room recognition contract
; Description ...: Generated constants for an inert, read-only native recognition bridge.
; Remarks .......: Generated by tools/generate_cleanroom_recognition_autoit.py from config/cleanroom-recognition.json.
;                  Do not edit by hand. This contract never authorizes input or legacy DLL dispatch.
; ===============================================================================================================================
#include-once

Global Const $CLEANROOM_RECOGNITION_SCHEMA_VERSION = 1
Global Const $CLEANROOM_RECOGNITION_ADAPTER_ID = "mybot.cleanroom-recognition.v1"
Global Const $CLEANROOM_RECOGNITION_EXPORT_COUNT = 17
Global Const $CLEANROOM_RECOGNITION_STATUS_READ_ONLY_PURE = "READ_ONLY_PURE"
Global Const $CLEANROOM_RECOGNITION_STATUS_FIXTURE_REPLAY_ONLY = "FIXTURE_REPLAY_ONLY"
Global Const $CLEANROOM_RECOGNITION_STATUS_UNAVAILABLE = "UNAVAILABLE"
Global Const $CLEANROOM_RECOGNITION_STATUS_REJECTED = "REJECTED"
Global Const $CLEANROOM_RECOGNITION_UNAVAILABLE_EXPORTS = "DoOCR|GetProperty|SearchMultipleTilesBetweenLevels|SearchRedLines|getLocationDarkElixirStorage|getLocationDarkElixirStorageWithLevel|getLocationElixirExtractorWithLevel|getLocationMineExtractorWithLevel|getLocationSnowElixirExtractorWithLevel|getLocationSnowMineExtractorWithLevel|getLocationTownHall|getRedArea|getRedAreaSideBuilding|ocr"
Global Const $CLEANROOM_RECOGNITION_MAX_WIDTH = 2048
Global Const $CLEANROOM_RECOGNITION_MAX_HEIGHT = 2048
Global Const $CLEANROOM_RECOGNITION_MAX_PIXELS = 4194304
Global Const $CLEANROOM_RECOGNITION_MAX_RESULTS = 32
Global Const $CLEANROOM_RECOGNITION_MAX_POINTS = 256
Global Const $CLEANROOM_RECOGNITION_FIXTURE_ASSET_ID = "current-client.daily-reward.claim"
Global Const $CLEANROOM_RECOGNITION_FIXTURE_ID = "home.daily-reward"
Global Const $CLEANROOM_RECOGNITION_FIXTURE_IMAGE_SHA256 = "33a759cb71627aa48a7f032966e50ceb540b9c736d125ca98bd532347c5429c9"
Global Const $CLEANROOM_RECOGNITION_FIXTURE_METADATA_SHA256 = "c7fa7ff9f383c3df7d15fe686a5de89094d200a30bdfce8ff5871e3630c3adc7"
Global Const $CLEANROOM_RECOGNITION_FIXTURE_WIDTH = 860
Global Const $CLEANROOM_RECOGNITION_FIXTURE_HEIGHT = 732
